### ISSUE TITLE
Iaas Migration - Azure to Azure

### ISSUE THREAD

**Issue by CHDAFNI-MSFT** [Azure/Azure-Migration-Guidance#1]
Azure Government supports Azure to Azure migration with Azure Site Recovery. The migration guidance talks about treating the VMs the legacy way, meaning treat them as if they are on-prem. Any reason why the Azure platform region to region migration wouldn't be the optimal choice as compared to the document's advice of treating the Azure VM like a physical / virtual

**Comment by SilviaDoomra** [comment]
When migrating from one Azure Government region to another, you should use Azure to Azure migration functionality in ASR. 

The guidance suggests the same in the first sentence of the 'Compute IaaS' section. It states: "Azure VMs can be migrated from one Azure region to another using Azure Site Recovery."

The recommendation to migrate using ASR like you are moving a physical server applies to scenarios when the migration needs to happen across non-geographic pairs and across cloud-type boundaries, such as Government to public or vice versa.
